# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: Dina Nashaat
description: The professional publishing platform
production_url: 
source_url: 

# Social info
navigation: True # show the navbar links
github: dina-nashaat # replace by your username

# Disqus
disqus: False
disqus_shortname: jekyller # replace with your disqus username

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

safe: False
lsi: False
branch: master
relative_source: ../jasper2/
destination: ../jasper2-pages/
production_url: 
source_url: 

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
